// export const states = [
//     {"label": "Tel-Aviv, Israel", "code": "TLV" },
//     {"label": "Paris, France", "code": "CDG" },
//     {"label": "San Francisco, United States", "code": "SFO" },
//     {"label": "Sao Paulo, Brazil", "code": "GRU" },
//     {"label": "Barcelona, Spain", "code": "BCN" },
//     {"label": "Toronto, Canada", "code": "YYZ" },
//     {"label": "Seoul, South Korea", "code": "ICN" },
//     {"label": "Shanghai, China", "code": "PVG" },
//     {"label": "Lisbon", "code":"LSB"  },
//     {"label": "Rome, Italy", "code": "FCO" },
//     {"label": "Singapore", "code": "SIN" },   
//     {"label": "Amsterdam, Netherlands", "code": "AMS" },
//     {"label": "Bangkok, Thailand", "code": "BKK" },     
//     {"label": "Beijing, China", "code": "PEK" },      
//     {"label": "Berlin, Germany ", "code": "BER" },     
//     {"label": "Cape Town, South Africa", "code": "CPT" },     
//     {"label": "Dubai, United Arab Emirates", "code": "DXB" },     
//     {"label": "Frankfurt, Germany", "code": "FRA"  },      
//     {"label": "Hong Kong, China", "code": "HKG" },     
//     {"label": "Istanbul, Turkey", "code": "IST" },     
//     {"label": "Jakarta, Indonesia", "code": "CGK" },     
//     {"label": "Johannesburg, South Africa", "code": "JNB" },     
//     {"label": "Kuala Lumpur, Malaysia", "code": "KUL" },     
//     {"label": "London, United Kingdom", "code": "LHR" },     
//     {"label": "Los Angeles, United States", "code": "LAX" },     
//     {"label": "Madrid, Spain", "code": "MAD" },     
//     {"label": "Mexico City, Mexico", "code": "MEX" },      
//     {"label": "Miami, United States", "code": "MIA" },     
//     {"label": "Moscow, Russia", "code": "DME" },     
//     {"label": "Mumbai, India", "code": "BOM" },      
//     {"label": "New York City, United States", "code": "JFK" },
//     {"label": "Sydney, Australia", "code": "SYD" },
//     {"label": "Tokyo, Japan", "code": "NRT" },
//     {"label": "Istanbul, Turkey", "code": "IST" },
//     {"label": "Chicago, United States", "code": "ORD" },
//     {"label": "Athens, Greece", "code": "ATH" }
// ]

export const states = [
    {"label": "Tel-Aviv, Israel", "code": "TLV" },
    {"label": "Paris, France", "code": "CDG" },
    {"label": "San Francisco, United States", "code": "SFO" },
    {"label": "Sao Paulo, Brazil", "code": "GRU" },
    {"label": "Barcelona, Spain", "code": "BCN" },
    {"label": "Toronto, Canada", "code": "YYZ" },
    {"label": "Seoul, South Korea", "code": "ICN" },
    {"label": "Shanghai, China", "code": "PVG" },
    {"label": "Lisbon, Portugal", "code": "LIS" },
    {"label": "Rome, Italy", "code": "FCO" },
    {"label": "Singapore", "code": "SIN" },   
    {"label": "Amsterdam, Netherlands", "code": "AMS" },
    {"label": "Bangkok, Thailand", "code": "BKK" },     
    {"label": "Beijing, China", "code": "PEK" },      
    {"label": "Berlin, Germany ", "code": "BER" },     
    {"label": "Cape Town, South Africa", "code": "CPT" },     
    {"label": "Dubai, United Arab Emirates", "code": "DXB" },     
    {"label": "Frankfurt, Germany", "code": "FRA"  },      
    {"label": "Hong Kong, China", "code": "HKG" },     
    {"label": "Istanbul, Turkey", "code": "IST" },     
    {"label": "Jakarta, Indonesia", "code": "CGK" },     
    {"label": "Johannesburg, South Africa", "code": "JNB" },     
    {"label": "Kuala Lumpur, Malaysia", "code": "KUL" },     
    {"label": "London, United Kingdom", "code": "LHR" },     
    {"label": "Los Angeles, United States", "code": "LAX" },     
    {"label": "Madrid, Spain", "code": "MAD" },     
    {"label": "Mexico City, Mexico", "code": "MEX" },      
    {"label": "Miami, United States", "code": "MIA" },     
    {"label": "Moscow, Russia", "code": "DME" },     
    {"label": "Mumbai, India", "code": "BOM" },      
    {"label": "New York City, United States", "code": "JFK" },
    {"label": "Sydney, Australia", "code": "SYD" },
    {"label": "Tokyo, Japan", "code": "NRT" },
    {"label": "Istanbul, Turkey", "code": "IST" },
    {"label": "Chicago, United States", "code": "ORD" },
    {"label": "Athens, Greece", "code": "ATH" },
    {"label": "Nairobi, Kenya", "code": "NBO" },
    {"label": "Munich, Germany", "code": "MUC" },
    {"label": "Geneva, Switzerland", "code": "GVA" },
    {"label": "Brussels, Belgium", "code": "BRU" },
    {"label": "Oslo, Norway", "code": "OSL" },
    {"label": "Helsinki, Finland", "code": "HEL" },
    {"label": "Budapest, Hungary", "code": "BUD" },
    {"label": "Auckland, New Zealand", "code": "AKL" },
    {"label": "Doha, Qatar", "code": "DOH" },
    {"label": "Cairo, Egypt", "code": "CAI" },
    {"label": "Colombo, Sri Lanka", "code": "CMB" },
    {"label": "Auckland, New Zealand", "code": "AKL" },
    {"label": "Bangalore, India", "code": "BLR" },
    {"label": "Dublin, Ireland", "code": "DUB" },
    {"label": "Frankfurt, Germany", "code": "FRA" },
    {"label": "Vienna, Austria", "code": "VIE" },
    {"label": "Perth, Australia", "code": "PER" },
    {"label": "Warsaw, Poland", "code": "WAW" },
    {"label": "Vancouver, Canada", "code": "YVR" },

// other states go here
];