export const users = {
    "39": "chango",
    "40": "etamar",
    "41": "Dorw",
    "42": "Eyalyosefi5",
    "43": "Lupo",
    "45": "Bargig",
    "46": "Leo",
    "47": "Dav1x",
    "48": "tomer",
    "49": "Falul",
    "53": "Ronbi",
    "55": "Itay Biton",
    "56": "Ronmik",
    "59": "TBH",
    "61": "Michael Fhima",
    "62": "Avihu",
    "64": "Oznativ",
}